### ISSUE TITLE
Switch to make english text first or last

### ISSUE THREAD

**Issue by wansinby** [DanielNT/ALTranslationSnippets#1]
Hi Daniel,
one little idea: maybe some developers would like first to insert the EnglishText and after this the TranslatedText, others would like the way it is at the moment. What do you think about a switch "Jump to EnglishText first" - if true, the EnglishText is the first, if false it is the last like at the actual code?
What is your opinion?
Best regards, Wolfram

**Comment by DanielNT** [comment]
I think that it's possible, I will take a look and make the change in a few days.

**Comment by DanielNT** [comment]
I have updated yesterday the extension to version 1.0.2, with a new command and this option. Check it, so I can fix bugs if there are any.

**Comment by wansinby** [comment]
Dear Daniel,
I got the Update before I was reading your comment, and tested it. It works great, as expected. Thank you very much. This helps us a lot.
I will close this issue. If I find any bugs I will open a new issue.
Best regards, Wolfram
